SET statement_timeout = 0;
SELECT pg_catalog.set_config('search_path', '', false);
SELECT app.backfill();

ALTER TYPE app.mood ADD VALUE IF NOT EXISTS 'archived';
ALTER TYPE app.mood RENAME TO mood_state;
DROP TYPE app.mood_state;

ALTER SCHEMA app OWNER TO app_owner;
ALTER FUNCTION app.touch(uuid) OWNER TO app_owner;
ALTER PUBLICATION app_events OWNER TO app_owner;

COMMENT ON SCHEMA app IS 'fixture';
COMMENT ON COLUMN app.items.name IS 'fixture';

ALTER TABLE app.items
  ADD CONSTRAINT items_tenant_fk FOREIGN KEY (tenant_id) REFERENCES app.tenants(id),
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN name TYPE varchar(200),
  ALTER COLUMN name SET DEFAULT '',
  ALTER COLUMN name DROP DEFAULT,
  ALTER COLUMN name SET NOT NULL,
  ALTER COLUMN name DROP NOT NULL,
  DROP CONSTRAINT items_old_check,
  VALIDATE CONSTRAINT items_tenant_fk;

ALTER DEFAULT PRIVILEGES FOR ROLE app_owner IN SCHEMA app
  GRANT SELECT ON TABLES TO app_reader;

GRANT USAGE ON SCHEMA app TO app_reader;
GRANT USAGE ON SEQUENCE app.item_seq TO app_reader;
GRANT EXECUTE ON FUNCTION app.touch(uuid) TO app_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA app TO app_reader;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA app TO app_reader;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app TO app_reader;

INSERT INTO app.items (id, tenant_id) VALUES ('1', '2');
UPDATE app.items SET name = 'fixture';
DO $$ BEGIN NULL; END $$;
