import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { adsClient, adsKeys, adsProviders, adsDestinations, adsWarnings, compatibleSources, defaultAdsPeriod, validAdsPeriod, type AdsClient, type AdsConnection, type AdsProvider, type AdsLink, type AdsLinkInput, type AdsDestination, type AdsPeriod } from '@/lib/marketingOps/ads';
import { leadKeys, type LeadClient, type LeadSource } from '@/lib/marketingOps/leads';
import { LeadError } from './LeadUi';
import { LeadImportDialog } from './LeadImportDialog';
import { count, leadDialog, leadSelect, shortDate, useDialogReturnFocus, useProposalKey } from './leadUiHelpers';

const ready = (connection: AdsConnection | undefined) => !!connection && !!connection.selectedAccountId && ['connected', 'partial'].includes(connection.status);
export function AdsLinksPanel({ campaignId, api = adsClient, leads, readOnly, onNewSource }: { campaignId: string; api?: AdsClient; leads: LeadClient; readOnly: boolean; onNewSource: () => void }) {
  const connections = useQuery({ queryKey: adsKeys.connections, queryFn: () => api.connections() });
  const sources = useQuery({ queryKey: leadKeys.sources(campaignId), queryFn: () => leads.sources(campaignId) });
  const links = useQuery({ queryKey: adsKeys.links(campaignId), queryFn: () => api.links(campaignId) });
  const [dialog, setDialog] = useState<'create' | { action: 'sync' | 'disable' | 'results'; link: AdsLink } | null>(null); const [outcome, setOutcome] = useState('');
  const resultButtons = useRef(new Map<string, HTMLButtonElement>());
  const close = () => setDialog(null); const done = (message: string) => { close(); setOutcome(message); };
  const providersReady = connections.data?.data.filter(ready) ?? [];
  const activeLink = dialog && typeof dialog === 'object' ? links.data?.data.find(link => link.id === dialog.link.id) ?? dialog.link : null;
  return <section className="space-y-5 border-t border-border pt-7" aria-labelledby="ads-links-title">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="ads-links-title" className="text-xl font-medium">Anúncios vinculados</h2><p className="mt-2 max-w-xl text-sm text-muted-foreground">Vincule anúncios a uma fonte para buscar métricas e revisar contatos de formulários.</p></div>{!readOnly && <Button variant="outline" className="min-h-11" disabled={!providersReady.length || sources.isLoading || links.isLoading} onClick={() => { setOutcome(''); setDialog('create'); }}><Plus aria-hidden="true" />Vincular anúncios</Button>}</header>
    <p role="status" aria-live="polite" aria-atomic="true" className={outcome ? 'text-sm text-status-success' : 'sr-only'}>{outcome}</p>
    <LeadError error={links.error || connections.error || sources.error} retry={() => { void links.refetch(); void connections.refetch(); void sources.refetch(); }} />
    {links.isLoading && <p role="status" className="text-sm">Carregando vínculos…</p>}
    {!connections.isLoading && !connections.isError && !providersReady.length && <p className="text-sm text-muted-foreground">Escolha uma conta autorizada em <Link className="inline-flex min-h-11 items-center text-brand-accent underline underline-offset-4" to="/settings/integrations">Integrações</Link> para vincular anúncios.</p>}
    {!links.isLoading && !links.isError && !links.data?.data.length && <p className="text-sm text-muted-foreground">Nenhum anúncio vinculado a esta campanha.</p>}
    <ul className="divide-y divide-border">{links.data?.data.map(link => {
      const connection = connections.data?.data.find(row => row.provider === link.provider); const account = connection?.accounts.find(row => row.id === link.externalAccountId);
      const canSync = ready(connection) && connection?.selectedAccountId === link.externalAccountId;
      return <li key={link.id} className="space-y-3 py-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-words font-medium">{sources.data?.data.find(source => source.id === link.sourceId)?.name ?? 'Fonte vinculada'}</h3><p className="mt-1 break-words text-sm text-muted-foreground">{adsProviders[link.provider]} · {adsDestinations[link.destination]}{account ? ` · ${account.name}` : ''}</p><p className="mt-1 break-all text-xs text-muted-foreground">Campanha no provedor: {link.externalCampaignId}</p></div><span className={`text-xs ${link.enabled ? 'text-status-success' : 'text-muted-foreground'}`}>{link.enabled ? 'Vínculo ativo' : 'Vínculo desabilitado'}</span></div><p className="text-xs text-muted-foreground">{link.lastSyncAt ? `Última sincronização: ${shortDate(link.lastSyncAt)}` : 'Ainda sem sincronização.'}</p>{link.safeError && <p className="text-sm text-status-warning">{adsWarnings[link.safeError] ?? 'A última sincronização não foi concluída. Atualize e confira a conexão.'}</p>}{link.enabled && !canSync && !connections.isLoading && <p className="text-sm text-status-warning">A conexão precisa estar autorizada na mesma conta deste vínculo para sincronizar. Confira <Link to="/settings/integrations" className="text-brand-accent underline">Integrações</Link>.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" className="min-h-11" ref={element => { if (element) resultButtons.current.set(link.id, element); else resultButtons.current.delete(link.id); }} onClick={() => setDialog({ action: 'results', link })}>Ver resultados</Button>{!readOnly && link.enabled && <><Button variant="outline" className="min-h-11" disabled={!canSync} onClick={() => setDialog({ action: 'sync', link })}>Sincronizar</Button><Button variant="ghost" className="min-h-11" onClick={() => setDialog({ action: 'disable', link })}>Desabilitar vínculo</Button></>}</div></li>;
    })}</ul>
    {dialog === 'create' && <CreateAdsLinkDialog campaignId={campaignId} api={api} connections={providersReady} sources={sources.data?.data ?? []} onClose={close} onSuccess={() => done('Anúncios vinculados à fonte.')} onNewSource={() => { close(); onNewSource(); }} />}
    {dialog && typeof dialog === 'object' && dialog.action === 'sync' && <AdsSyncDialog key={dialog.link.id} campaignId={campaignId} api={api} link={dialog.link} connection={connections.data?.data.find(row => row.provider === dialog.link.provider)} onClose={close} onSuccess={() => done('Sincronização concluída. Confira os resultados e os contatos para revisão.')} />}
    {dialog && typeof dialog === 'object' && dialog.action === 'disable' && activeLink && <DisableAdsLinkDialog campaignId={campaignId} api={api} link={activeLink} focusFallback={() => resultButtons.current.get(activeLink.id) ?? null} onClose={close} onSuccess={() => done('Vínculo desabilitado. O histórico foi preservado.')} />}
    {dialog && typeof dialog === 'object' && dialog.action === 'results' && <AdsResultsDialog key={dialog.link.id} campaignId={campaignId} api={api} leads={leads} link={dialog.link} readOnly={readOnly} onClose={close} />}
  </section>;
}
function CreateAdsLinkDialog({ campaignId, api, connections, sources, onClose, onSuccess, onNewSource }: { campaignId: string; api: AdsClient; connections: AdsConnection[]; sources: LeadSource[]; onClose: () => void; onSuccess: () => void; onNewSource: () => void }) {
  const qc = useQueryClient(); const returnFocus = useDialogReturnFocus(); const key = useProposalKey();
  const [provider, setProvider] = useState<AdsProvider | ''>(''); const [externalId, setExternalId] = useState(''); const [sourceId, setSourceId] = useState(''); const [destination, setDestination] = useState<AdsDestination>('native_form');
  const [proposal, setProposal] = useState<AdsLinkInput | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<unknown>(null);
  const [reviewAccountId, setReviewAccountId] = useState<string | null>(null);
  const connection = connections.find(row => row.provider === provider); const account = connection?.accounts.find(row => row.id === connection.selectedAccountId);
  const campaigns = useQuery({ queryKey: adsKeys.campaigns(provider || 'meta', connection?.selectedAccountId ?? null, connection?.version ?? 0), queryFn: () => api.campaigns(provider as AdsProvider), enabled: !!provider && ready(connection) });
  const candidates = provider && connection?.selectedAccountId ? compatibleSources(sources, provider, connection.selectedAccountId, externalId, destination) : [];
  const source = sources.find(row => row.id === sourceId);
  const confirm = async () => {
    if (!proposal || busy) return;
    if (!ready(connection) || connection?.selectedAccountId !== reviewAccountId) { setProposal(null); setError(new Error('A conta mudou. Confira a conexão e revise o vínculo novamente.')); return; }
    setBusy(true); setError(null);
    try { await api.createLink(campaignId, proposal, key(proposal)); await qc.invalidateQueries({ queryKey: adsKeys.all }); onSuccess(); }
    catch (issue) { setError(issue); if ((issue as { status?: number }).status === 409) { await qc.invalidateQueries({ queryKey: adsKeys.connections }); await qc.invalidateQueries({ queryKey: adsKeys.links(campaignId) }); } } finally { setBusy(false); }
  };
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className={leadDialog} onCloseAutoFocus={returnFocus} onInteractOutside={event => { if (busy) event.preventDefault(); }}><DialogHeader><DialogTitle>Vincular anúncios</DialogTitle><DialogDescription>Escolha a campanha da conta autorizada e a fonte existente que receberá sua atribuição.</DialogDescription></DialogHeader><LeadError error={error || campaigns.error} retry={!proposal ? () => { void campaigns.refetch(); } : undefined} />{proposal ? <section aria-label="Revisão do vínculo" className="space-y-5"><h3 className="font-medium">Confira o vínculo</h3><dl className="grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Provedor e conta</dt><dd className="mt-1 break-words">{adsProviders[proposal.provider]} · {account?.name ?? 'Conta autorizada'}</dd></div><div><dt className="text-muted-foreground">Campanha de anúncios</dt><dd className="mt-1 break-words">{campaigns.data?.data.find(row => row.id === proposal.externalCampaignId)?.name ?? 'Campanha selecionada'}</dd></div><div><dt className="text-muted-foreground">Fonte</dt><dd className="mt-1 break-words">{source?.name}</dd></div><div><dt className="text-muted-foreground">Destino</dt><dd className="mt-1">{adsDestinations[proposal.destination]}</dd></div></dl><p className="text-sm text-muted-foreground">O vínculo permite sincronizações explícitas. Contatos de formulários exigem revisão humana antes de entrar na campanha.</p><div className="flex flex-wrap justify-end gap-3"><Button variant="outline" className="min-h-11" disabled={busy} onClick={() => setProposal(null)}>Voltar à seleção</Button><Button className="min-h-11" disabled={busy} aria-busy={busy} onClick={() => { void confirm(); }}>{busy ? 'Vinculando…' : 'Confirmar vínculo'}</Button></div></section> : <form className="space-y-5" onSubmit={event => { event.preventDefault(); if (provider && externalId && candidates.some(row => row.id === sourceId)) { setReviewAccountId(connection?.selectedAccountId ?? null); setProposal({ provider, sourceId, externalCampaignId: externalId, destination }); } }}><fieldset className="space-y-4" disabled={busy}>
    <div className="space-y-2"><Label htmlFor="ads-provider">Provedor de anúncios</Label><select id="ads-provider" required className={leadSelect} value={provider} onChange={event => { setProvider(event.target.value as AdsProvider); setExternalId(''); setSourceId(''); }}><option value="">Selecione o provedor</option>{connections.map(row => <option key={row.provider} value={row.provider}>{adsProviders[row.provider]}</option>)}</select>{account && <p className="break-words text-xs text-muted-foreground">{account.name} · {account.currency} · {account.timeZone ?? 'Fuso não informado'}</p>}</div>
    <div className="space-y-2"><Label htmlFor="ads-campaign">Campanha de anúncios</Label><select id="ads-campaign" required className={leadSelect} disabled={!provider || campaigns.isFetching} value={externalId} onChange={event => { setExternalId(event.target.value); setSourceId(''); }}><option value="">{campaigns.isFetching ? 'Carregando campanhas…' : 'Selecione uma campanha'}</option>{campaigns.data?.data.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{provider && campaigns.data && !campaigns.data.data.length && <p className="text-sm text-muted-foreground">Nenhuma campanha acessível nesta conta.</p>}</div>
    <div className="space-y-2"><Label htmlFor="ads-destination">Destino dos anúncios</Label><select id="ads-destination" className={leadSelect} value={destination} onChange={event => { setDestination(event.target.value as AdsDestination); setSourceId(''); }}>{Object.entries(adsDestinations).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></div>
    <div className="space-y-2"><Label htmlFor="ads-source">Fonte da campanha</Label><select id="ads-source" required className={leadSelect} disabled={!externalId} value={sourceId} onChange={event => setSourceId(event.target.value)}><option value="">Selecione uma fonte compatível</option>{candidates.map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{externalId && !candidates.length && <div className="space-y-2 text-sm"><p className="text-muted-foreground">Crie uma fonte ativa de leads identificados para {provider ? adsProviders[provider] : 'este provedor'}, compatível com a conta, a campanha e o destino.</p><Button type="button" variant="outline" className="min-h-11" onClick={onNewSource}>Nova fonte</Button></div>}</div>
    </fieldset>{destination === 'native_form' && connection && !connection.capabilities.nativeLeads && <p className="text-sm text-status-warning">Métricas disponíveis conforme a permissão. A importação de formulários requer autorização para consultar contatos.</p>}{destination !== 'native_form' && source?.kind === 'manual' && <p className="text-sm text-muted-foreground">Contatos por importação; instrumente a página ou o link para captura automática.</p>}<div className="flex flex-wrap justify-end gap-3"><Button type="button" variant="outline" className="min-h-11" onClick={onClose}>Cancelar</Button><Button className="min-h-11" type="submit" disabled={!provider || !externalId || !candidates.some(row => row.id === sourceId)}>Revisar vínculo</Button></div></form>}</DialogContent></Dialog>;
}
function AdsSyncDialog({ campaignId, api, link, connection, onClose, onSuccess }: { campaignId: string; api: AdsClient; link: AdsLink; connection?: AdsConnection; onClose: () => void; onSuccess: () => void }) {
  const qc = useQueryClient(); const returnFocus = useDialogReturnFocus(); const key = useProposalKey();
  const account = connection?.accounts.find(row => row.id === link.externalAccountId); const timeZone = account?.timeZone;
  const [period, setPeriod] = useState<AdsPeriod>(() => timeZone ? defaultAdsPeriod(timeZone) : { from: '', to: '' }); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  const sync = async (event: React.FormEvent) => { event.preventDefault(); if (busy) return; if (!validAdsPeriod(period)) { setError(new Error('Informe um período válido de até 30 dias, sem datas futuras.')); return; } setBusy(true); setError(null); try { await api.sync(campaignId, link.id, period, key({ linkId: link.id, period })); await qc.invalidateQueries({ queryKey: adsKeys.all }); await qc.invalidateQueries({ queryKey: leadKeys.all }); onSuccess(); } catch (issue) { setError(issue); if ((issue as { status?: number }).status === 409) await qc.invalidateQueries({ queryKey: adsKeys.all }); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className={`${leadDialog} sm:max-w-xl`} onCloseAutoFocus={returnFocus} onInteractOutside={event => { if (busy) event.preventDefault(); }}><DialogHeader><DialogTitle>Sincronizar anúncios</DialogTitle><DialogDescription>Confira o período antes de consultar {adsProviders[link.provider]}. A sincronização atualiza métricas e prepara contatos para revisão.</DialogDescription></DialogHeader><LeadError error={error} /><form onSubmit={sync} className="space-y-5"><p className="break-words text-sm text-text-secondary">Moeda: {account?.currency ?? 'Não informada'} · Fuso: {timeZone ?? 'Não informado; escolha o período explicitamente'}</p><fieldset disabled={busy} className="grid min-w-0 gap-4 sm:grid-cols-2"><div className="min-w-0 space-y-2"><Label htmlFor="ads-from">Início da sincronização</Label><Input id="ads-from" className="min-h-11 min-w-0" required type="date" value={period.from} onChange={event => setPeriod(previous => ({ ...previous, from: event.target.value }))} /></div><div className="min-w-0 space-y-2"><Label htmlFor="ads-to">Fim da sincronização</Label><Input id="ads-to" className="min-h-11 min-w-0" required type="date" value={period.to} onChange={event => setPeriod(previous => ({ ...previous, to: event.target.value }))} /></div></fieldset><p className="text-xs leading-relaxed text-muted-foreground">Até 30 dias, sem datas futuras. O período sugerido cobre os últimos 7 dias encerrados no fuso da conta. Relatórios manuais sobrepostos serão preservados; conversões do provedor não são vendas.</p><div className="flex flex-wrap justify-end gap-3"><Button type="button" variant="outline" className="min-h-11" disabled={busy} onClick={onClose}>Cancelar</Button><Button type="submit" className="min-h-11" disabled={busy} aria-busy={busy}>{busy ? 'Sincronizando…' : 'Confirmar sincronização'}</Button></div></form></DialogContent></Dialog>;
}
function DisableAdsLinkDialog({ campaignId, api, link, onClose, onSuccess, focusFallback }: { campaignId: string; api: AdsClient; link: AdsLink; onClose: () => void; onSuccess: () => void; focusFallback: () => HTMLElement | null }) {
  const qc = useQueryClient(); const returnFocus = useDialogReturnFocus(focusFallback); const key = useProposalKey(); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  const disable = async () => { if (busy) return; setBusy(true); setError(null); try { await api.disableLink(campaignId, link.id, link.version, key({ id: link.id, version: link.version })); await qc.invalidateQueries({ queryKey: adsKeys.all }); onSuccess(); } catch (issue) { setError(issue); if ((issue as { status?: number }).status === 409) await qc.invalidateQueries({ queryKey: adsKeys.links(campaignId) }); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className={`${leadDialog} sm:max-w-lg`} onCloseAutoFocus={returnFocus} onInteractOutside={event => { if (busy) event.preventDefault(); }}><DialogHeader><DialogTitle>Desabilitar vínculo?</DialogTitle><DialogDescription>Novas sincronizações deste vínculo serão interrompidas. A fonte, os contatos e os resultados anteriores permanecerão no histórico.</DialogDescription></DialogHeader><LeadError error={error} /><div className="flex flex-wrap justify-end gap-3"><Button variant="outline" className="min-h-11" disabled={busy} onClick={onClose}>Cancelar</Button><Button className="min-h-11" disabled={busy} aria-busy={busy} onClick={() => { void disable(); }}>{busy ? 'Desabilitando…' : 'Confirmar desabilitação'}</Button></div></DialogContent></Dialog>;
}
function AdsResultsDialog({ campaignId, api, leads, link, readOnly, onClose }: { campaignId: string; api: AdsClient; leads: LeadClient; link: AdsLink; readOnly: boolean; onClose: () => void }) {
  const returnFocus = useDialogReturnFocus(); const [previewId, setPreviewId] = useState<string | null>(null);
  const reviewedPreview = useRef<string | null>(null);
  const reviewButtons = useRef(new Map<string, HTMLButtonElement>());
  const results = useQuery({ queryKey: adsKeys.results(campaignId, link.id), queryFn: () => api.results(campaignId, link.id) });
  return <><Dialog open={!previewId} onOpenChange={open => { if (!open && !previewId) onClose(); }}><DialogContent className={leadDialog + " min-w-0 [&>*]:min-w-0"} onCloseAutoFocus={event => { if (previewId) event.preventDefault(); else returnFocus(event); }} onOpenAutoFocus={event => { const trigger = reviewedPreview.current && reviewButtons.current.get(reviewedPreview.current); if (trigger) { event.preventDefault(); trigger.focus(); } }}><DialogHeader><DialogTitle>Resultados dos anúncios</DialogTitle><DialogDescription>{adsProviders[link.provider]} · Métricas medidas pelo provedor e recibos de sincronização. Conversões do provedor não são vendas.</DialogDescription></DialogHeader><LeadError error={results.error} retry={() => { void results.refetch(); }} />{results.isLoading && <p role="status">Carregando resultados…</p>}{results.data && <><section className="space-y-3" aria-label="Métricas diárias"><h3 className="font-medium">Métricas diárias</h3><p className="text-xs text-muted-foreground">Cada linha mantém a moeda e o fuso de origem. Valores ausentes aparecem como —; moedas diferentes não são somadas.</p>{results.data.data.daily.length ? <div role="region" aria-label="Tabela de métricas" tabIndex={0} className="max-w-full overflow-x-auto rounded-xl border border-border focus-visible:outline focus-visible:outline-2 focus-visible:outline-ring"><table className="w-full text-left text-xs"><caption className="sr-only">Métricas por dia, moeda e fuso da conta</caption><thead className="bg-background text-text-secondary"><tr>{['Dia', 'Moeda', 'Fuso', 'Investimento', 'Impressões', 'Cliques', 'Conversões'].map(label => <th scope="col" key={label} className="whitespace-nowrap px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{results.data.data.daily.map(day => <tr key={`${day.date}-${day.currency}-${day.timeZone}`} className="border-t border-border"><th scope="row" className="whitespace-nowrap px-3 py-3 font-normal">{shortDate(day.date)}</th><td className="px-3 py-3">{day.currency}</td><td className="px-3 py-3">{day.timeZone}</td><td className="whitespace-nowrap px-3 py-3 tabular-nums">{day.spend == null ? '—' : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: day.currency }).format(day.spend)}</td><td className="px-3 py-3 tabular-nums">{count(day.impressions)}</td><td className="px-3 py-3 tabular-nums">{count(day.clicks)}</td><td className="px-3 py-3 tabular-nums">{count(day.conversions)}</td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">Nenhuma métrica disponível. Confira os recibos e as permissões; ausência de medição não é zero.</p>}</section><section className="space-y-4" aria-label="Recibos de sincronização"><h3 className="font-medium">Sincronizações</h3>{!results.data.data.receipts.length && <p className="text-sm text-muted-foreground">Nenhuma sincronização concluída.</p>}{results.data.data.receipts.map(receipt => {
    const previews = receipt.previewIds?.length ? receipt.previewIds : receipt.previewId ? [receipt.previewId] : [];
    return <article key={receipt.id} className="space-y-3 border-t border-border pt-4"><h4 className="text-sm font-medium">{receipt.status === 'needs_review' ? 'Concluída com itens para revisar' : 'Sincronização concluída'} · {shortDate(receipt.completedAt)}</h4><p className="text-xs text-muted-foreground">{receipt.days} dias recebidos · {receipt.reports} relatórios atualizados</p>{receipt.warnings.length > 0 && <ul className="space-y-2 text-sm text-status-warning">{receipt.warnings.map((warning, index) => <li key={`${warning}-${index}`}>{adsWarnings[warning] ?? 'Parte da consulta não pôde ser concluída. Confira as permissões e tente novamente.'}</li>)}</ul>}{previews.length > 0 && <div className="space-y-2"><p className="text-sm text-muted-foreground">Contatos aguardam revisão. Cada lote contém até 500 contatos; nenhum foi importado automaticamente.</p>{!readOnly && <div className="flex flex-wrap gap-2">{previews.map((id, index) => <Button key={id} variant="outline" className="min-h-11" ref={element => { if (element) reviewButtons.current.set(id, element); else reviewButtons.current.delete(id); }} onClick={() => { reviewedPreview.current = id; setPreviewId(id); }}>Revisar contatos · lote {index + 1}</Button>)}</div>}</div>}</article>;
  })}</section></>}</DialogContent></Dialog>{previewId && <LeadImportDialog key={previewId} campaignId={campaignId} api={leads} existingPreviewId={previewId} onClose={() => setPreviewId(null)} />}</>;
}
