import { useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AnalyticsProviderSwitch } from './AnalyticsProviderSwitch';
import { WebAnalyticsResults } from '@/components/dashboard/WebAnalyticsResults';
import { analyticsClient, analyticsKeys, analyticsProviders, defaultAnalyticsPeriod, validAnalyticsPeriod, type AnalyticsClient, type AnalyticsProvider, type AnalyticsPeriod, type AnalyticsLink } from '@/lib/marketingOps/analytics';
import { LeadError } from './LeadUi';
import { leadContainer, leadDialog, leadSelect, useDialogReturnFocus, useProposalKey } from './leadUiHelpers';

export function CampaignWebAnalytics({ campaignId, canManage, api = analyticsClient }: { campaignId: string; canManage: boolean; api?: AnalyticsClient }) {
  const qc = useQueryClient(); const connections = useQuery({ queryKey: analyticsKeys.connections, queryFn: api.connections });
  const links = useQuery({ queryKey: analyticsKeys.links(campaignId), queryFn: () => api.links(campaignId) });
  const timezone = connections.data?.data.find(row => row.provider === 'ga4')?.resources.find(row => row.id === connections.data?.data.find(item => item.provider === 'ga4')?.selectedResourceId)?.timeZone ?? 'UTC';
  const [filter, setFilter] = useState<AnalyticsPeriod | null>(null); const period = filter ?? defaultAnalyticsPeriod(timezone); const valid = validAnalyticsPeriod(period, timezone);
  const results = useQuery({ queryKey: analyticsKeys.campaign(campaignId, period), queryFn: () => api.campaignResults(campaignId, period), enabled: valid, retry: false });
  const [provider, setProvider] = useState<AnalyticsProvider>('ga4'); const [linking, setLinking] = useState(false); const [disable, setDisable] = useState<AnalyticsLink | null>(null);
  const [error, setError] = useState<unknown>(null); const [outcome, setOutcome] = useState(''); const [busy, setBusy] = useState(false); const lock = useRef(false); const trigger = useRef<HTMLButtonElement>(null);
  const measured = results.data?.data[provider];
  const deactivate = async () => { if (!disable || lock.current) return; lock.current = true; setBusy(true); setError(null); try { await api.disableLink(campaignId, disable); setDisable(null); setOutcome('Vínculo desativado. O histórico foi preservado.'); await qc.invalidateQueries({ queryKey: analyticsKeys.all }); } catch (issue) { setError(issue); if ((issue as { status?: number }).status === 409) { const fresh = await links.refetch(); setDisable(fresh.data?.data.find(row => row.id === disable.id) ?? null); } } finally { lock.current = false; setBusy(false); } };
  return <section aria-label="Navegação atribuída à campanha" className={[leadContainer, 'pb-24 md:pb-8'].join(' ')}>
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold tracking-tight">Navegação da campanha</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Veja as sessões do site atribuídas aos parâmetros UTM desta campanha. Eventos de navegação não são leads nem vendas.</p></div>{canManage && <Button ref={trigger} className="min-h-11" disabled={links.isLoading || connections.isLoading} onClick={() => setLinking(true)}>Vincular navegação</Button>}</header>
    <LeadError error={links.error || connections.error} retry={() => { void links.refetch(); void connections.refetch(); }} /><p role="status" aria-live="polite" className={outcome ? 'text-sm text-status-success' : 'sr-only'}>{outcome}</p>
    {links.isLoading && <p role="status">Carregando vínculos…</p>}
    {links.data && <details className="text-sm" open={!links.data.data.some(row => row.enabled)}><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Vínculos e atribuição</summary><div className="space-y-3 rounded-xl border border-border bg-card p-5">{!links.data.data.length && <p className="text-sm text-muted-foreground">Nenhum parâmetro vinculado. Use o mesmo valor de utm_campaign das URLs divulgadas.</p>}{links.data.data.map(row => <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3 last:border-0 last:pb-0" key={row.id}><div className="min-w-0"><p className="break-all text-sm">{analyticsProviders[row.provider]} · <span className="font-mono">{row.utmCampaign}</span></p><p className="mt-1 text-xs text-muted-foreground">{row.enabled ? 'Ativo' : 'Desativado'} · {row.resourceId}{row.enabled && connections.data?.data.find(item => item.provider === row.provider)?.selectedResourceId !== row.resourceId ? ' · Revise: o recurso selecionado mudou' : ''}</p></div>{row.enabled && canManage && <Button variant="ghost" className="min-h-11" disabled={busy} onClick={() => { setError(null); setDisable(row); }}>Desativar vínculo</Button>}</div>)}<Button asChild variant="link" className="min-h-11 px-0"><Link to="/settings/integrations?tab=analytics">Gerenciar conexões do site</Link></Button></div></details>}
    <div className="flex flex-wrap items-end justify-between gap-4"><AnalyticsProviderSwitch value={provider} onChange={value => { setProvider(value); setFilter(null); }} />{provider === 'ga4' && <div className="flex flex-wrap gap-3"><div className="space-y-2"><Label htmlFor="campaign-analytics-from" className="text-xs">De</Label><Input id="campaign-analytics-from" className="h-11" type="date" value={period.from} onChange={event => setFilter({ ...period, from: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="campaign-analytics-to" className="text-xs">Até</Label><Input id="campaign-analytics-to" className="h-11" type="date" value={period.to} max={defaultAnalyticsPeriod(timezone).to} onChange={event => setFilter({ ...period, to: event.target.value })} /></div></div>}</div>
    {!valid && <LeadError error={new Error('Escolha até 30 dias completos no fuso da propriedade.')} />}<LeadError error={results.error} retry={() => { void results.refetch(); }} />{results.isLoading && <p role="status">Carregando resultados atribuídos…</p>}
    {valid && measured ? <WebAnalyticsResults results={measured} /> : results.data && <div className="rounded-xl border border-border bg-card p-6"><p className="text-sm text-muted-foreground">Ainda não há leitura atribuída a esta campanha neste recorte. Confira o vínculo UTM e atualize a leitura do site.</p><Button asChild variant="link" className="mt-2 min-h-11 px-0"><Link to={`/marketing-ops/analytics?provider=${provider}`}>Atualizar leitura do site</Link></Button></div>}
    {linking && <AnalyticsLinkDialog campaignId={campaignId} api={api} available={connections.data?.data.filter(row => ['connected', 'partial'].includes(row.status) && row.selectedResourceId).map(row => row.provider) ?? []} fallback={() => trigger.current} onClose={() => setLinking(false)} onSuccess={() => { setLinking(false); setOutcome('Vínculo criado. Os resultados aparecerão após a leitura do site.'); void qc.invalidateQueries({ queryKey: analyticsKeys.all }); }} />}
    {disable && <DisableAnalyticsLinkDialog busy={busy} error={error} fallback={() => trigger.current} onClose={() => { if (!lock.current) setDisable(null); }} onConfirm={() => { void deactivate(); }} />}
  </section>;
}

function AnalyticsLinkDialog({ campaignId, api, available, onClose, onSuccess, fallback }: { campaignId: string; api: AnalyticsClient; available: AnalyticsProvider[]; onClose: () => void; onSuccess: () => void; fallback: () => HTMLElement | null }) {
  const returnFocus = useDialogReturnFocus(fallback); const proposal = useProposalKey(); const [provider, setProvider] = useState<AnalyticsProvider>(available[0] ?? 'ga4'); const [utm, setUtm] = useState(''); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false); const lock = useRef(false);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (lock.current || !available.includes(provider) || !utm.trim()) return; lock.current = true; setBusy(true); setError(null); const input = { provider, utmCampaign: utm.trim() }; try { await api.createLink(campaignId, input, proposal(input)); onSuccess(); } catch (issue) { setError(issue); if ((issue as { code?: string }).code === 'idempotency_conflict') proposal.reset(); } finally { lock.current = false; setBusy(false); } };
  return <Dialog open onOpenChange={open => { if (!open && !lock.current) onClose(); }}><DialogContent className={`${leadDialog} sm:max-w-xl`} onCloseAutoFocus={returnFocus} onInteractOutside={event => { if (lock.current) event.preventDefault(); }} onEscapeKeyDown={event => { if (lock.current) event.preventDefault(); }}><DialogHeader><DialogTitle>Vincular navegação</DialogTitle><DialogDescription>O vínculo usa o valor exato de utm_campaign, incluindo letras maiúsculas e minúsculas. O mesmo segmento não pode estar ativo em duas campanhas.</DialogDescription></DialogHeader><LeadError error={error} />{!available.length ? <div className="space-y-3"><p className="text-sm text-muted-foreground">Conecte um recurso Analytics ou Clarity antes de criar o vínculo.</p><Button asChild className="min-h-11"><Link to="/settings/integrations?tab=analytics">Abrir integrações</Link></Button></div> : <form onSubmit={event => { void save(event); }} className="space-y-5"><div className="space-y-2"><Label htmlFor="utm-provider">Provedor</Label><select id="utm-provider" className={leadSelect} value={provider} disabled={busy} onChange={event => setProvider(event.target.value as AnalyticsProvider)}>{available.map(row => <option value={row} key={row}>{analyticsProviders[row]}</option>)}</select></div><div className="space-y-2"><Label htmlFor="utm-campaign-value">Valor de utm_campaign</Label><Input id="utm-campaign-value" className="min-h-11" required maxLength={200} value={utm} onChange={event => setUtm(event.target.value)} disabled={busy} aria-describedby="utm-example" /><p id="utm-example" className="break-words text-xs text-muted-foreground">Exemplo: oferta_outubro em site.com/?utm_campaign=oferta_outubro. Use o valor da URL, não o nome interno da campanha.</p></div><div className="flex flex-wrap justify-end gap-3"><Button variant="outline" className="min-h-11" disabled={busy} onClick={onClose}>Cancelar</Button><Button className="min-h-11" type="submit" disabled={busy || !utm.trim()}>{busy ? 'Vinculando…' : 'Confirmar vínculo'}</Button></div></form>}</DialogContent></Dialog>;
}
function DisableAnalyticsLinkDialog({ busy, error, onClose, onConfirm, fallback }: { busy: boolean; error: unknown; onClose: () => void; onConfirm: () => void; fallback: () => HTMLElement | null }) {
  const returnFocus = useDialogReturnFocus(fallback);
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className={`${leadDialog} sm:max-w-lg`} onCloseAutoFocus={returnFocus} onInteractOutside={event => { if (busy) event.preventDefault(); }} onEscapeKeyDown={event => { if (busy) event.preventDefault(); }}><DialogHeader><DialogTitle>Desativar vínculo?</DialogTitle><DialogDescription>Este parâmetro deixará de compor a leitura vigente da campanha. O histórico será preservado.</DialogDescription></DialogHeader><LeadError error={error} /><div className="flex flex-wrap justify-end gap-3"><Button variant="outline" className="min-h-11" disabled={busy} onClick={onClose}>Cancelar</Button><Button className="min-h-11" disabled={busy} onClick={onConfirm}>{busy ? 'Desativando…' : 'Confirmar desativação'}</Button></div></DialogContent></Dialog>;
}
