CREATE SCHEMA iam AUTHORIZATION nexus_owner;
CREATE SCHEMA app_private AUTHORIZATION nexus_owner;
CREATE SCHEMA audit AUTHORIZATION nexus_owner;

REVOKE ALL ON SCHEMA infra FROM PUBLIC;
REVOKE ALL ON SCHEMA iam FROM PUBLIC;
REVOKE ALL ON SCHEMA app_private FROM PUBLIC;
REVOKE ALL ON SCHEMA audit FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA infra
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA infra
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA infra
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA iam
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA iam
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA iam
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA app_private
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA app_private
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA app_private
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA audit
  REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA audit
  REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE nexus_owner IN SCHEMA audit
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

