import { useId } from 'react';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { leadChannels, type LeadResults, type LeadChannel } from '@/lib/marketingOps/leads';
import { count, currency, shortDate } from '@/components/marketing-ops/leadUiHelpers';

const panel = 'min-w-0 rounded-xl border border-border bg-card p-5 sm:p-6';
const colors: Record<LeadChannel, string> = { meta_ads: 'hsl(var(--brand-secondary))', google_ads: 'hsl(var(--brand-accent))', linkedin_ads: 'hsl(var(--prometeus-slate))', email: 'hsl(var(--prometeus-mist))', whatsapp: 'hsl(var(--primary))', organic: 'hsl(var(--text-muted))', google_maps: 'hsl(var(--prometeus-navy))', other: 'hsl(var(--foreground))' };
const tooltip = { background: 'hsl(var(--popover))', border: '1px solid hsl(var(--input))', borderRadius: 10, color: 'hsl(var(--foreground))', fontSize: 12 };
export function LeadIndicators({ results, campaign = false }: { results: LeadResults; campaign?: boolean }) {
  const measuredContacts = results.coverage.sources > 0 || results.capturedLeads > 0 || results.contactsCold > 0;
  return <section aria-label={campaign ? 'Indicadores da campanha' : 'Indicadores principais'} aria-live="polite" className="grid grid-cols-2 gap-x-5 gap-y-7 border-y border-border py-7 lg:grid-cols-4">
    {[
      { id: 'leads', label: 'Novos leads', value: measuredContacts ? results.capturedLeads : null, money: false, note: 'Pessoas identificadas' },
      { id: 'sales', label: 'Vendas no período', value: results.sales, money: false, note: 'Informes medidos' },
      { id: 'revenue', label: 'Receita no período', value: results.revenue, money: true, note: 'Informes medidos' },
      { id: 'spend', label: 'Investimento informado', value: results.spend, money: true, note: 'Informes medidos' },
    ].map(item => <article key={item.id} className="min-w-0"><h2 className="text-xs text-text-secondary sm:text-sm">{item.label}</h2><p data-testid={`live-kpi-${item.id}`} className="mt-3 break-words text-2xl font-medium leading-tight tracking-tight tabular-nums sm:text-3xl">{item.money ? currency(item.value) : count(item.value)}</p><p className="mt-2 text-xs text-muted-foreground">{item.value === null ? 'Ainda não medido' : item.note}</p></article>)}
  </section>;
}
export function LeadCharts({ results }: { results: LeadResults }) {
  const id = useId().replace(/:/g, ''); const total = results.channels.reduce((sum, row) => sum + row.leads, 0);
  return <div className="grid min-w-0 gap-6 xl:grid-cols-[1.15fr_1fr]">
    <section aria-label="Evolução dos leads" className={panel}><h2 className="text-lg font-semibold tracking-tight">Evolução dos leads</h2><p className="mt-1 text-xs text-muted-foreground">Leads identificados por semana de captação.</p>
      {results.weekly.length ? <div className="mt-5 h-[240px] min-w-0" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><AreaChart data={results.weekly} margin={{ top: 12, left: -18, right: 10, bottom: 0 }}><defs><linearGradient id={`real-leads-${id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--primary))" stopOpacity={.25} /><stop offset="100%" stopColor="hsl(var(--primary))" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 6" /><XAxis dataKey="week" tickFormatter={value => shortDate(value).slice(0, 5)} tick={{ fill: 'hsl(var(--text-muted))', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis allowDecimals={false} tick={{ fill: 'hsl(var(--text-muted))', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltip} itemStyle={{ color: 'hsl(var(--foreground))' }} labelFormatter={value => `Semana de ${shortDate(String(value))}`} /><Area type="monotone" name="Leads" dataKey="leads" stroke="hsl(var(--brand-accent))" fill={`url(#real-leads-${id})`} strokeWidth={2.5} isAnimationActive={false} dot={{ r: 3, fill: 'hsl(var(--brand-accent))' }} /></AreaChart></ResponsiveContainer></div> : <div className="flex h-[240px] items-center justify-center text-sm text-muted-foreground">Ainda não há leads medidos para este gráfico.</div>}
      <details className="mt-4 text-xs"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Ver valores por semana</summary>{results.weekly.length ? <table className="w-full text-left"><caption className="sr-only">Leads por semana de captação</caption><thead><tr><th className="py-3 font-medium">Semana</th><th className="text-right font-medium">Leads</th></tr></thead><tbody>{results.weekly.map(row => <tr key={row.week} className="border-t border-border"><th scope="row" className="py-3 font-normal">{shortDate(row.week)}</th><td className="text-right tabular-nums">{count(row.leads)}</td></tr>)}</tbody></table> : <p className="py-3 text-muted-foreground">Sem registros no período.</p>}</details>
    </section>
    <section aria-label="Distribuição de leads por canal" className={panel}><h2 className="text-lg font-semibold tracking-tight">Origem dos leads</h2><p className="mt-1 text-xs text-muted-foreground">Contatos frios e cliques ficam fora desta distribuição.</p>
      {total ? <div className="mt-5 grid min-w-0 items-center gap-4 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><div className="relative h-[240px] min-w-0" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><PieChart><defs><pattern id={`organic-${id}`} width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" fill={colors.organic} /><path d="M0 6L6 0" stroke="hsl(var(--background))" strokeWidth="1" /></pattern><pattern id={`whatsapp-${id}`} width="7" height="7" patternUnits="userSpaceOnUse"><rect width="7" height="7" fill={colors.whatsapp} /><circle cx="3.5" cy="3.5" r="1" fill="hsl(var(--prometeus-mist))" /></pattern></defs><Pie rootTabIndex={-1} data={results.channels.filter(row => row.leads > 0)} dataKey="leads" nameKey="channel" innerRadius="68%" outerRadius="90%" paddingAngle={2} stroke="hsl(var(--card))" isAnimationActive={false}>{results.channels.filter(row => row.leads > 0).map(row => <Cell key={row.channel} fill={row.channel === 'organic' ? `url(#organic-${id})` : row.channel === 'whatsapp' ? `url(#whatsapp-${id})` : colors[row.channel]} />)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-medium tabular-nums">{count(total)}</span><span className="mt-1 text-xs text-muted-foreground">leads</span></div></div><ul className="space-y-3">{results.channels.map(row => <li key={row.channel} className="flex min-w-0 items-start gap-2 text-xs"><span aria-hidden="true" className="mt-1 h-2 w-2 shrink-0 rounded-full border border-text-muted" style={{ background: colors[row.channel], ...(row.channel === 'whatsapp' ? { backgroundImage: 'radial-gradient(hsl(var(--prometeus-mist)) 1px, transparent 1px)', backgroundSize: '4px 4px' } : {}) }} /><div className="min-w-0 flex-1"><span>{leadChannels[row.channel]}</span><span className="mt-1 block text-muted-foreground">{count(row.leads)} leads · {new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 }).format(row.leads / total * 100)}%</span></div></li>)}</ul></div> : <div className="flex h-[240px] items-center justify-center text-sm text-muted-foreground">Sem registros para distribuir.</div>}
      <details className="mt-4 text-xs"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Ver valores por canal</summary><table className="w-full text-left"><caption className="sr-only">Leads identificados por canal</caption><thead><tr><th className="py-3 font-medium">Canal</th><th className="text-right font-medium">Leads</th></tr></thead><tbody>{results.channels.map(row => <tr key={row.channel} className="border-t border-border"><th scope="row" className="py-3 font-normal">{leadChannels[row.channel]}</th><td className="text-right tabular-nums">{count(row.leads)}</td></tr>)}</tbody></table></details>
    </section>
  </div>;
}
export function LeadCoverage({ results }: { results: LeadResults }) {
  return <details className="text-sm"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Fontes e cobertura dos dados</summary><div className="mt-3 space-y-3 rounded-xl border border-border bg-card p-5"><p className="text-text-secondary">{count(results.coverage.sources)} fontes · {count(results.coverage.reports)} relatórios · {count(results.contactsCold)} contatos frios · {count(results.whatsappClicks)} cliques em WhatsApp</p><p className="text-xs leading-relaxed text-muted-foreground">Leads são pessoas distintas identificadas no recorte. Métricas agregadas vêm dos relatórios; qualificados e vendas podem incluir pessoas que ainda não foram importadas. Eles não representam uma coorte individual nem autorizam uma conclusão automática sobre a saúde da operação.</p><dl className="grid grid-cols-2 gap-3 text-xs">{(['qualified', 'sales', 'revenue', 'spend'] as const).map(metric => <div key={metric}><dt className="text-muted-foreground">{{ qualified: 'Qualificados', sales: 'Vendas', revenue: 'Receita', spend: 'Investimento' }[metric]}</dt><dd className="mt-1">{results.coverage.metricReports[metric]} relatórios medidos</dd></div>)}</dl>{results.coverage.partialReportsExcluded > 0 && <p className="text-xs text-status-warning">{count(results.coverage.partialReportsExcluded)} relatórios com janela parcialmente fora do filtro foram excluídos. Amplie o período para incluí-los integralmente.</p>}<p className="text-xs text-muted-foreground">Ausência de valores não representa zero. Contatos frios e cliques não somam como leads.</p></div></details>;
}
