import { useId } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { analyticsWarnings, type AnalyticsResults } from '@/lib/marketingOps/analytics';
import { count, shortDate } from '@/components/marketing-ops/leadUiHelpers';

const panel = 'min-w-0 rounded-xl border border-border bg-card p-5 sm:p-6';
const colors = ['hsl(var(--brand-accent))', 'hsl(var(--primary))', 'hsl(var(--prometeus-slate))', 'hsl(var(--prometeus-mist))', 'hsl(var(--text-muted))', 'hsl(var(--foreground))'];
const tooltip = { background: 'hsl(var(--popover))', color: 'hsl(var(--foreground))', border: '1px solid hsl(var(--input))', borderRadius: 10, fontSize: 12 };
const stamp = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'UTC' }).format(new Date(value));
export function WebAnalyticsResults({ results }: { results: AnalyticsResults }) {
  const id = useId().replace(/:/g, ''); const clarity = results.provider === 'clarity'; const total = results.totals;
  const engagement = total && total.sessions > 0 && total.engagedSessions != null ? total.engagedSessions / total.sessions * 100 : null;
  const indicators = clarity ? [
    { label: 'Sessões', value: total?.sessions, suffix: '' }, { label: 'Sessões de bots', value: total?.botSessions, suffix: '' },
    { label: 'Origens informadas', value: total ? results.channels.length : null, suffix: '' }, { label: 'Campanhas UTM', value: total ? results.campaigns.filter(row => row.utmCampaign && !['(not set)', '(none)'].includes(row.utmCampaign)).length : null, suffix: '' },
  ] : [
    { label: 'Sessões', value: total?.sessions, suffix: '' }, { label: 'Engajamento', value: engagement, suffix: '%' },
    { label: 'Visualizações', value: total?.pageViews, suffix: '' }, { label: 'Eventos-chave', value: total?.keyEvents, suffix: '' },
  ];
  const channels = [...results.channels].sort((a, b) => b.sessions - a.sessions).map(row => ({ ...row, name: `${row.source || '(não informado)'} / ${row.medium || '(não informado)'}` }));
  const chartChannels = channels.slice(0, 5);
  if (channels.length > 5) chartChannels.push({ source: '', medium: '', name: 'Outras origens', sessions: channels.slice(5).reduce((sum, row) => sum + row.sessions, 0) });
  const chartCampaigns = [...results.campaigns].sort((a, b) => b.sessions - a.sessions).slice(0, 6);
  return <div className="space-y-7">
    {clarity && results.window && <p className="text-sm leading-relaxed text-text-secondary">Janela móvel de 24 horas: {stamp(results.window.from)} até {stamp(results.window.to)} (UTC). Cada leitura é um snapshot; as janelas não são somadas.</p>}
    {results.stale && <p role="status" className="text-sm text-status-warning">Leitura desatualizada. Consulte a última atualização antes de tomar decisões.</p>}
    {results.warnings.some(warning => ['analytics_thresholded', 'analytics_sampled', 'analytics_other_row', 'analytics_clarity_row_limit', 'analytics_incomplete_coverage', 'analytics_segment_not_measured'].includes(warning)) && <p role="status" className="text-sm text-status-warning">Leitura parcial ou cobertura limitada. Veja as limitações em “Como interpretar esta leitura”.</p>}
    <section aria-label={clarity ? 'Indicadores de experiência' : 'Indicadores de navegação'} className="grid grid-cols-2 gap-x-5 gap-y-7 border-y border-border py-7 lg:grid-cols-4">{indicators.map(item => <article key={item.label} className="min-w-0"><h2 className="text-xs text-text-secondary sm:text-sm">{item.label}</h2><p className="mt-3 text-2xl font-medium tabular-nums sm:text-3xl">{item.value == null ? '—' : `${new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 1 }).format(item.value)}${item.suffix}`}</p><p className="mt-2 text-xs text-muted-foreground">{item.value == null ? 'Não informado' : clarity ? 'Na última janela medida' : 'No período selecionado'}</p></article>)}</section>
    {!total ? <section className={panel}><h2 className="font-medium">Sem medições neste recorte</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Conecte um recurso, confira se o rastreamento está instalado no site e atualize os resultados. Ausência de medição não representa zero.</p></section> : <div className="grid gap-6 xl:grid-cols-2">
      {!clarity ? <section className={panel}><h2 className="text-lg font-semibold">Evolução das sessões</h2><p className="mt-1 text-xs text-muted-foreground">Dias completos no fuso da propriedade.</p>{results.daily.length ? <div className="mt-5 h-[260px]" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><AreaChart data={results.daily} margin={{ top: 12, left: -18, right: 10 }}><defs><linearGradient id={`analytics-${id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={colors[0]} stopOpacity={.22} /><stop offset="100%" stopColor={colors[0]} stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="date" tickFormatter={value => shortDate(value).slice(0, 5)} tick={{ fill: 'hsl(var(--text-muted))', fontSize: 11 }} axisLine={false} tickLine={false} minTickGap={24} /><YAxis tick={{ fill: 'hsl(var(--text-muted))', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} /><Tooltip contentStyle={tooltip} labelFormatter={shortDate} formatter={value => [count(Number(value)), 'Sessões']} /><Area type="monotone" dataKey="sessions" stroke={colors[0]} strokeWidth={2} fill={`url(#analytics-${id})`} isAnimationActive={false} /></AreaChart></ResponsiveContainer></div> : <p className="flex min-h-[260px] items-center justify-center text-sm text-muted-foreground">Sem sessões registradas no período.</p>}
        <details className="mt-3 text-xs"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Ver valores por dia</summary><table className="w-full text-left"><caption className="sr-only">Sessões por dia</caption><thead><tr><th className="py-3">Dia</th><th className="text-right">Sessões</th></tr></thead><tbody>{results.daily.map(row => <tr key={row.date} className="border-t border-border"><th scope="row" className="py-3 font-normal">{shortDate(row.date)}</th><td className="text-right tabular-nums">{count(row.sessions)}</td></tr>)}</tbody></table></details>
      </section> : <section className={panel}><h2 className="text-lg font-semibold">Campanhas na janela</h2><p className="mt-1 text-xs text-muted-foreground">Parâmetros UTM informados pelo Clarity.</p>{chartCampaigns.length ? <div className="mt-5 h-[260px]" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartCampaigns} layout="vertical" margin={{ left: 0, right: 12 }}><XAxis type="number" hide /><YAxis type="category" dataKey="utmCampaign" width={110} tick={{ fill: 'hsl(var(--text-secondary))', fontSize: 11 }} tickLine={false} axisLine={false} /><Tooltip contentStyle={tooltip} formatter={value => [count(Number(value)), 'Sessões']} /><Bar dataKey="sessions" fill={colors[0]} radius={[0, 4, 4, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div> : <p className="flex min-h-[260px] items-center justify-center text-sm text-muted-foreground">Nenhum parâmetro de campanha informado.</p>}
        <details className="mt-3 text-xs"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Ver valores por campanha</summary><table className="w-full text-left"><caption className="sr-only">Sessões por campanha</caption><thead><tr><th className="py-3">Campanha UTM</th><th className="text-right">Sessões</th></tr></thead><tbody>{results.campaigns.map((row, index) => <tr key={`${row.utmCampaign}-${index}`} className="border-t border-border"><th scope="row" className="break-all py-3 font-normal">{row.utmCampaign}</th><td className="text-right tabular-nums">{count(row.sessions)}</td></tr>)}</tbody></table></details>
      </section>}
      <section className={panel}><h2 className="text-lg font-semibold">Origem das sessões</h2><p className="mt-1 text-xs text-muted-foreground">Distribuição das origens informadas nesta leitura.</p>{chartChannels.some(row => row.sessions > 0) ? <div className="mt-5 grid items-center gap-4 sm:grid-cols-2"><div className="h-[260px]" aria-hidden="true"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartChannels} dataKey="sessions" nameKey="name" innerRadius="65%" outerRadius="88%" paddingAngle={2} stroke="hsl(var(--card))" isAnimationActive={false} rootTabIndex={-1}>{chartChannels.map((row, index) => <Cell key={row.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tooltip} formatter={value => [count(Number(value)), 'Sessões']} /></PieChart></ResponsiveContainer></div><ul className="space-y-3">{chartChannels.map((row, index) => <li className="flex items-start gap-2 text-xs" key={row.name}><span aria-hidden="true" className="mt-1 h-2 w-2 shrink-0 rounded-full" style={{ background: colors[index % colors.length] }} /><span className="min-w-0 break-words">{row.name}<span className="mt-1 block text-muted-foreground">{count(row.sessions)} sessões</span></span></li>)}</ul></div> : <p className="flex min-h-[260px] items-center justify-center text-sm text-muted-foreground">Sem origens para distribuir.</p>}
        <details className="mt-3 text-xs"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Ver valores por origem</summary><table className="w-full text-left"><caption className="sr-only">Sessões por origem</caption><thead><tr><th className="py-3">Origem / mídia</th><th className="text-right">Sessões</th></tr></thead><tbody>{channels.map((row, index) => <tr key={`${row.name}-${index}`} className="border-t border-border"><th scope="row" className="break-words py-3 font-normal">{row.name}</th><td className="text-right tabular-nums">{count(row.sessions)}</td></tr>)}</tbody></table></details>
      </section>
    </div>}
    <details className="text-sm"><summary className="flex min-h-11 cursor-pointer items-center text-brand-accent">Como interpretar esta leitura</summary><div className="space-y-3 rounded-xl border border-border bg-card p-5 text-sm leading-relaxed text-muted-foreground"><p>Sessões e eventos-chave não representam leads identificados nem vendas. Engajamento considera sessões engajadas divididas pelas sessões; não é uma medida automática de saúde comercial.</p><p>{clarity ? 'Snapshots Clarity representam janelas móveis em UTC. Não compare seu total diretamente com um período fechado do GA4. Contagens de atrito ausentes não significam zero.' : 'Dados GA4 podem sofrer ajustes e limites de privacidade. Uma leitura incompleta pode alterar a distribuição de origens. A medição depende da tag e da configuração de eventos do seu site.'}</p>{results.lastSyncAt && <p>Última leitura: {stamp(results.lastSyncAt)} UTC.</p>}{results.warnings.length > 0 && <ul className="list-disc space-y-2 pl-5">{results.warnings.map((warning, index) => <li key={`${warning}-${index}`}>{analyticsWarnings[warning] ?? 'O provedor sinalizou uma limitação nesta leitura. Confira a cobertura antes de comparar os indicadores.'}</li>)}</ul>}</div></details>
  </div>;
}
